### ISSUE TITLE
2 new custom map images

### ISSUE THREAD

**Issue by thegoog1337** [cato-a/CODPM-MapImages#16]
![zh_inkhouse](https://github.com/user-attachments/assets/0a844e99-96b9-4b68-98a9-9c3868d66252)
![gg_splatterball](https://github.com/user-attachments/assets/4410cc17-526c-4030-934b-14c7152598ac)

**Comment by thegoog1337** [comment]
F... its stretched

**Comment by thegoog1337** [comment]
![zh_inkhouse](https://github.com/user-attachments/assets/5eb07173-c3dd-41fc-bdd8-24592486f481)
![gg_splatterball](https://github.com/user-attachments/assets/bcd169e2-afa6-4d52-a5a0-370bbd64304d)

**Comment by cato-a** [comment]
Thanks for the images, but they look streched to me. Make sure the source aspect ratio is 4:3 in-game.

https://cod.pm/guide/32b0b3/how-to-set-a-custom-screen-resolution-in-game

You can also upload the full 4:3 image and I'll crop and downscale them. In GIMP you can set fixed aspect ratio in the crop tool and `480:200` value, then downscale.

**Comment by thegoog1337** [comment]
Aight thx for the guide!
Ill try again tomorrow.

**Comment by cato-a** [comment]
Added the images with correct AR.

https://github.com/cato-a/CODPM-MapImages/commit/ca44988dbfcddd43f578fcd4f2824e2bf68cb04b
