### ISSUE TITLE
DOB_Nuketown

### ISSUE THREAD

**Issue by vCoDMods** [cato-a/CODPM-MapImages#2]
CoD 1 Custom Map, DOB_Nuketown

![DOB_Nuketown](https://github.com/cato-a/CODPM-MapImages/assets/123815638/eaad28ae-1be9-4a7f-a629-f0aaeb8738a0)

**Comment by vCoDMods** [comment]
Another CoD Map.

mp_asch

![mp_asch](https://github.com/cato-a/CODPM-MapImages/assets/123815638/fb216cb7-3beb-4902-a0b5-84039aa04b98)

**Comment by vCoDMods** [comment]
CoD, cod_breakers_yard 

![cod_breakers_yard](https://github.com/cato-a/CODPM-MapImages/assets/123815638/e84667b0-9045-4b3d-8a3a-4c39fb6ac15d)

**Comment by cato-a** [comment]
Thanks :)
